server:
  port: 8092

property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c
propertyKyoujin: limkj

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green

fruit.testProperty: fruit test string

fruit.test-property2: aa

fruit.test_property3: bb

fruit.testproperty4: cc

# H2 메모리 DB를 사용하기 위한 설정
# https://docs.spring.io/spring-boot/docs/current/reference/html/ 참고...
# Common Application properties 섹션 참고하면됨..
datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true

facebook:
  client:
    clientId: clientIdTest
    clientSecret: clientSecretTest
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

google:
  client:
    clientId: clientIdTest
    clientSecret: clientSecretTest
    accessTokenUri: https://accounts.google.com/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao:
  client:
    clientId: clientIdTest
    accessTokenUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me